# Site settings
title:   Smruti Amarjyoti - Amar

description: > # this means to ignore newlines until "baseurl:"
  A reflection of my thoughts and experiments on the fascinating realm of Robotics and Artificial Intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amarjyotismruti.github.io" # the base hostname & protocol for your site
twitter_username:  samarjyoti
github_username:  Amarjyotismruti

# Build settings
markdown: kramdown

# Redirection
gems:
  - jekyll-redirect-from

exclude: [blog.md ,cs-dojo.md, uf-ml.md, paper-summaries.md]